import 'package:flutter/foundation.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:world_traveller_project/models/user_profile.dart';

/// Kept for backwards compatibility with call sites and error handling
/// that still expect this type; thrown when a profile could not be
/// created/updated because of a conflicting unique value.
class UsernameTakenException implements Exception {
  final String username;
  const UsernameTakenException(this.username);

  @override
  String toString() => 'The value "$username" is already taken.';
}

/// Talks to the `profiles` and `favourites` tables.
///
/// See SUPABASE_SETUP.sql and SUPABASE_SETUP_PHASE1.sql for the exact
/// schema these methods expect.
class ProfileService {
  static final ProfileService _instance = ProfileService._internal();
  factory ProfileService() => _instance;
  ProfileService._internal();

  SupabaseClient get _client => Supabase.instance.client;

  static const String _profilesTable = 'profiles';
  static const String _favouritesTable = 'favourites';

  // -------------------------------------------------------------------
  // Profiles
  // -------------------------------------------------------------------

  /// Creates (or updates) the profile row for the signed in user.
  /// `public_id` and `role` are never sent: the ID is generated by a DB
  /// trigger on first insert and the role is admin-managed only.
  ///
  /// [avatarUrl], [email] and [bio] are only written when explicitly
  /// given. This used to send `null` for whichever of them the caller
  /// didn't pass — which, on an upsert, ERASES that column — so saving
  /// just the name from "My Account" was silently wiping out the
  /// profile picture. Omitting the key entirely leaves the existing
  /// value in the database untouched.
  Future<UserProfile> saveProfile({
    required String userId,
    required String firstName,
    required String lastName,
    String? avatarUrl,
    String? email,
    String? bio,
  }) async {
    final data = <String, dynamic>{
      'id': userId,
      'first_name': firstName.trim(),
      'last_name': lastName.trim(),
    };
    if (avatarUrl != null) data['avatar_url'] = avatarUrl;
    if (email != null) data['email'] = email;
    if (bio != null) data['bio'] = bio;

    final row = await _client
        .from(_profilesTable)
        .upsert(data)
        .select()
        .single();

    return UserProfile.fromSupabase(Map<String, dynamic>.from(row));
  }

  /// Creates the profile row ONLY if it doesn't already exist — never
  /// overwrites one that's there. Used as a last-resort fallback right
  /// after sign-in when the profile could not be read (e.g. a slow
  /// connection), so a real, already-saved name can never be replaced
  /// by a guessed placeholder just because this one read failed.
  Future<void> createProfileIfMissing({
    required String userId,
    required String firstName,
    required String lastName,
    String? email,
  }) async {
    await _client.from(_profilesTable).upsert(
      {
        'id': userId,
        'first_name': firstName.trim(),
        'last_name': lastName.trim(),
        if (email != null) 'email': email,
      },
      onConflict: 'id',
      ignoreDuplicates: true,
    );
  }

  /// Updates only the profile picture, used by the "edit avatar" action
  /// on the account screen.
  Future<UserProfile> updateAvatar({
    required String userId,
    required String avatarUrl,
  }) async {
    final row = await _client
        .from(_profilesTable)
        .update({'avatar_url': avatarUrl})
        .eq('id', userId)
        .select()
        .single();

    return UserProfile.fromSupabase(Map<String, dynamic>.from(row));
  }

  /// Blocks or unblocks a traveller's account. Only the administrator
  /// may call this — enforced both here (see SocialController) and by
  /// the `profiles` table's Row Level Security policy, which only lets
  /// an admin update someone else's `is_blocked`/`role` columns.
  Future<void> setBlocked({
    required String userId,
    required bool blocked,
  }) async {
    await _client
        .from(_profilesTable)
        .update({'is_blocked': blocked})
        .eq('id', userId);
  }

  /// Loads one profile by its user id. Returns null when missing.
  Future<UserProfile?> fetchProfile(String userId) async {
    try {
      final row = await _client
          .from(_profilesTable)
          .select()
          .eq('id', userId)
          .maybeSingle();

      if (row == null) return null;
      return UserProfile.fromSupabase(Map<String, dynamic>.from(row));
    } catch (e) {
      debugPrint('Could not load profile $userId: $e');
      return null;
    }
  }

  /// Loads a profile by its short public ID (e.g. "MRC-7F2A"), used to
  /// resolve a name clash in the search results.
  Future<UserProfile?> fetchProfileByPublicId(String publicId) async {
    try {
      final row = await _client
          .from(_profilesTable)
          .select()
          .eq('public_id', publicId.trim().toUpperCase())
          .maybeSingle();

      if (row == null) return null;
      return UserProfile.fromSupabase(Map<String, dynamic>.from(row));
    } catch (e) {
      debugPrint('Could not load profile by ID $publicId: $e');
      return null;
    }
  }

  /// Loads many profiles at once, used to label a whole grid of pictures.
  Future<Map<String, UserProfile>> fetchProfiles(Iterable<String> userIds) async {
    final ids = userIds.where((id) => id.isNotEmpty).toSet().toList();
    if (ids.isEmpty) return {};

    try {
      final rows = await _client
          .from(_profilesTable)
          .select()
          .inFilter('id', ids);

      final result = <String, UserProfile>{};
      for (final raw in rows as List) {
        final profile = UserProfile.fromSupabase(Map<String, dynamic>.from(raw as Map));
        result[profile.id] = profile;
      }
      return result;
    } catch (e) {
      debugPrint('Could not load profiles: $e');
      return {};
    }
  }

  /// Finds travellers by first and/or last name.
  ///
  /// "Find Travelers" is meant to search by name; when several people
  /// share the same name, [UserProfile.fullNameWithId] (or a direct
  /// lookup with [fetchProfileByPublicId]) is what tells them apart.
  Future<List<UserProfile>> searchProfiles(String query) async {
    final clean = query.trim().toLowerCase();
    if (clean.isEmpty) return [];

    // Someone can paste the unique ID directly to jump straight to the
    // right person even when many travellers share the same name.
    if (RegExp(r'^[a-z0-9]{4}-[a-z0-9]{4}$').hasMatch(clean)) {
      final byId = await fetchProfileByPublicId(clean);
      if (byId != null) return [byId];
    }

    try {
      final rows = await _client
          .from(_profilesTable)
          .select()
          .or('first_name.ilike.%$clean%,last_name.ilike.%$clean%')
          .order('first_name')
          .order('last_name')
          .limit(30);

      return (rows as List)
          .map((raw) => UserProfile.fromSupabase(Map<String, dynamic>.from(raw as Map)))
          .toList();
    } catch (e) {
      debugPrint('Could not search profiles: $e');
      return [];
    }
  }

  // -------------------------------------------------------------------
  // Favourites
  // -------------------------------------------------------------------

  /// Every media id the given user has liked.
  Future<Set<String>> fetchFavouriteIds(String userId) async {
    try {
      final rows = await _client
          .from(_favouritesTable)
          .select('media_id')
          .eq('user_id', userId);

      return (rows as List)
          .map((raw) => (raw as Map)['media_id']?.toString() ?? '')
          .where((id) => id.isNotEmpty)
          .toSet();
    } catch (e) {
      debugPrint('Could not load favourites: $e');
      return {};
    }
  }

  Future<void> addFavourite(String userId, String mediaId) async {
    await _client.from(_favouritesTable).upsert({
      'user_id': userId,
      'media_id': mediaId,
    });
  }

  Future<void> removeFavourite(String userId, String mediaId) async {
    await _client
        .from(_favouritesTable)
        .delete()
        .eq('user_id', userId)
        .eq('media_id', mediaId);
  }
}
