import 'package:world_traveller_project/enums/user_role.dart';

/// A traveller's profile.
///
/// Phase 1 replaces the old nickname with a real First name / Last name,
/// a profile picture, and an automatically generated unique ID
/// ([publicId]) used to tell two people with the same name apart.
class UserProfile {
  /// Same value as the Supabase auth user id.
  final String id;

  /// Short, human-friendly identifier generated by the database
  /// (e.g. "MRC-7F2A"). Never chosen by the user; used as a tie-breaker
  /// when several travellers share the same first/last name.
  final String publicId;

  final String firstName;
  final String lastName;

  /// URL of the profile picture. Editable by the user at any time.
  final String? avatarUrl;

  final UserRole role;
  final String? email;
  final String? bio;
  final DateTime? createdAt;

  /// True once the administrator has blocked this account for breaking
  /// the terms of use. A blocked traveller can no longer sign in (they
  /// can still browse the public "General World" as anyone else can,
  /// signed out) and can never add or edit content while blocked.
  final bool isBlocked;

  const UserProfile({
    required this.id,
    required this.publicId,
    required this.firstName,
    required this.lastName,
    this.avatarUrl,
    this.role = UserRole.standard,
    this.email,
    this.bio,
    this.createdAt,
    this.isBlocked = false,
  });

  factory UserProfile.fromSupabase(Map<String, dynamic> row) {
    return UserProfile(
      id: row['id']?.toString() ?? '',
      publicId: row['public_id'] as String? ?? '',
      firstName: (row['first_name'] as String?)?.trim().isNotEmpty == true
          ? (row['first_name'] as String).trim()
          : 'Traveller',
      lastName: (row['last_name'] as String?)?.trim() ?? '',
      avatarUrl: row['avatar_url'] as String?,
      role: UserRole.fromDb(row['role'] as String?),
      email: row['email'] as String?,
      bio: row['bio'] as String?,
      createdAt: row['created_at'] != null
          ? DateTime.tryParse(row['created_at'].toString())
          : null,
      isBlocked: row['is_blocked'] as bool? ?? false,
    );
  }

  /// What gets written back to Supabase. `public_id` and `role` are never
  /// sent from the client: the ID is generated by a DB trigger and the
  /// role can only be changed by an administrator directly in the
  /// database, never by the app itself.
  Map<String, dynamic> toSupabase() {
    return {
      'id': id,
      'first_name': firstName,
      'last_name': lastName,
      'avatar_url': avatarUrl,
      'email': email,
      'bio': bio,
    };
  }

  /// "Marco Rossi" — what every screen should show instead of the old
  /// "@nickname".
  String get fullName => [firstName, lastName].where((s) => s.trim().isNotEmpty).join(' ');

  /// "Marco Rossi (MRC-7F2A)" — used wherever two travellers could be
  /// confused with each other, e.g. search results with a name clash.
  String get fullNameWithId => publicId.isEmpty ? fullName : '$fullName ($publicId)';

  bool get isAdmin => role == UserRole.admin;

  /// Letter shown inside the round avatar when no picture is available.
  String get initial => firstName.isNotEmpty ? firstName[0].toUpperCase() : '?';

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserProfile && runtimeType == other.runtimeType && id == other.id;

  @override
  int get hashCode => id.hashCode;
}
